FROM europe-west1-docker.pkg.dev/automation-370217/custom/quarkus-micro-image-base:3.0
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/*-runner /work/application

EXPOSE 9090
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
